-- SELECCIONA LA BASE DE DATOS
USE RetamarValoracionesFP;

-- MUESTRA LAS TABLAS EXISTENTES
SHOW TABLES;

-- IMPRIME LOS DATOS DE CADA TABLA
SELECT * FROM alumnos;
SELECT * FROM ciclos;
SELECT * FROM profesores;
SELECT * FROM asignaturas;
SELECT * FROM valoraciones;

-- FINALIZADO
